// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: ws_header.proto

package platform_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`         // 指令類型，例如 "join_room"、"start_game"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 內層資料序列化後的 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_ws_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_ws_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_ws_header_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JoinRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	mi := &file_ws_header_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_ws_header_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_ws_header_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResp) Reset() {
	*x = JoinRoomResp{}
	mi := &file_ws_header_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResp) ProtoMessage() {}

func (x *JoinRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_ws_header_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResp.ProtoReflect.Descriptor instead.
func (*JoinRoomResp) Descriptor() ([]byte, []int) {
	return file_ws_header_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JoinRoomResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ws_header_proto protoreflect.FileDescriptor

const file_ws_header_proto_rawDesc = "" +
	"\n" +
	"\x0fws_header.proto\"5\n" +
	"\aMessage\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"&\n" +
	"\vJoinRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"@\n" +
	"\fJoinRoomResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x12Z\x10./platform_protob\x06proto3"

var (
	file_ws_header_proto_rawDescOnce sync.Once
	file_ws_header_proto_rawDescData []byte
)

func file_ws_header_proto_rawDescGZIP() []byte {
	file_ws_header_proto_rawDescOnce.Do(func() {
		file_ws_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_header_proto_rawDesc), len(file_ws_header_proto_rawDesc)))
	})
	return file_ws_header_proto_rawDescData
}

var file_ws_header_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ws_header_proto_goTypes = []any{
	(*Message)(nil),      // 0: Message
	(*JoinRoomReq)(nil),  // 1: JoinRoomReq
	(*JoinRoomResp)(nil), // 2: JoinRoomResp
}
var file_ws_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_header_proto_init() }
func file_ws_header_proto_init() {
	if File_ws_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_header_proto_rawDesc), len(file_ws_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_header_proto_goTypes,
		DependencyIndexes: file_ws_header_proto_depIdxs,
		MessageInfos:      file_ws_header_proto_msgTypes,
	}.Build()
	File_ws_header_proto = out.File
	file_ws_header_proto_goTypes = nil
	file_ws_header_proto_depIdxs = nil
}
